name: publish-glast

on:
    push:
        branches:
            - "release/glast"

    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        timeout-minutes: 10
        defaults:
            run:
                working-directory: glast

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install rust toolchain
              run: rustup update

            - name: Run tests
              run: cargo test

    publish:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: test
        defaults:
            run:
                shell: pwsh

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install rust toolchain
              run: rustup update

            - name: Publish
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN_GLAST }}
              run: cargo build
              working-directory: glast

    release:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        needs: publish
        defaults:
            run:
                shell: pwsh
        permissions:
            contents: write

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Package release
              id: release-script
              run: .\build\release.ps1

            - name: Publish release
              uses: softprops/action-gh-release@v0.1.14
              with:
                  name: "glast v${{ steps.release-script.outputs.VERSION }}"
                  body: ""
                  tag_name: "glast/v${{ steps.release-script.outputs.VERSION }}"
                  target_commitish: ${{ github.sha }}
                  files: "out/glast-v${{ steps.release-script.outputs.VERSION }}.zip"
                  fail_on_unmatched_files: true
