name: publish-glast

on:
    push:
        branches:
            - "release/glast"

    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

env:
    CARGO_INCREMENTAL: 0

jobs:
    test:
        name: "Run test suite"
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        timeout-minutes: 10

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install rust toolchain
              run: rustup update

            - name: Run tests
              run: cargo test
              working-directory: glast

    publish:
        name: "Build and publish to crates.io"
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: test
        defaults:
            run:
                shell: pwsh

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install rust toolchain
              run: rustup update

            - name: Publish
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN_GLAST }}
              run: cargo publish --verbose
              working-directory: glast

    gh-release:
        name: "Create github release"
        runs-on: ubuntu-latest
        timeout-minutes: 5
        needs: publish
        defaults:
            run:
                shell: pwsh
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Build script
              id: build-script
              run: /build/release-glast.ps1

            - name: Publish release
              uses: softprops/action-gh-release@v0.1.14
              with:
                  name: "glast v${{ steps.build-script.outputs.VERSION }}"
                  body: "PASTE CHANGELOG HERE"
                  tag_name: "glast/v${{ steps.build-script.outputs.VERSION }}"
                  target_commitish: ${{ github.sha }}
                  files: "/publish/glast-${{ steps.build-script.outputs.VERSION }}.zip"
                  fail_on_unmatched_files: true
